global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "webapp"
    static_configs:
      - targets: ["webapp:5000"]

  - job_name: "gitlab"
    metrics_path: "/-/metrics"
    static_configs:
      - targets: ["gitlab_loc:9090"]