global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'webapp'
    static_configs:
      - targets: ['webapp:5000']
  - job_name: 'gitlab_loc'
    static_configs:
      - targets: ['gitlab_loc:9093']
